<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:14:29.
 */
class databaseResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var databaseResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new databaseResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers databaseResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::set_bd_server
     * @todo   Implement testSet_bd_server().
     */
    public function testSet_bd_server() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::set_bd_name
     * @todo   Implement testSet_bd_name().
     */
    public function testSet_bd_name() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::set_bd_user
     * @todo   Implement testSet_bd_user().
     */
    public function testSet_bd_user() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::set_bd_password
     * @todo   Implement testSet_bd_password().
     */
    public function testSet_bd_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::CheckConnection
     * @todo   Implement testCheckConnection().
     */
    public function testCheckConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::OpenNewConnection
     * @todo   Implement testOpenNewConnection().
     */
    public function testOpenNewConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::OpenOtherSGBD
     * @todo   Implement testOpenOtherSGBD().
     */
    public function testOpenOtherSGBD() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::setActiveInstance
     * @todo   Implement testSetActiveInstance().
     */
    public function testSetActiveInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::dropActiveInstance
     * @todo   Implement testDropActiveInstance().
     */
    public function testDropActiveInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers databaseResource::load
     * @todo   Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
